### ISSUE TITLE
"Cannot get consentBanner of undefined"

### ISSUE THREAD

**Issue by Bholtland** [ambitiondev/vue-cookiebot-plugin#2]
When using this module with Nuxt, I'm getting a Typescript error as Typescript does not recognise $cookiebot as a property of 'Vue'. To try and solve this I set '$cookiebot' as a property to my component. Of course this only fixes the type error as this.$cookiebot is undefined. I set up the app exactly as the install.md says.

**Comment by bnachtweh** [comment]
@Bholtland thank you for submitting your issue. Did you add the module to your Nuxt configuration? See: https://nuxtjs.org/guides/directory-structure/plugins/

**Comment by bnachtweh** [comment]
@Bholtland as I haven't received a reply, so I'm going to assume that the issue is resolved. Please open a new issue when the problem persists. Thank you!
